#!/usr/bin/env node
/**
 * Generates .agents/skills/catalog.md from the skills themselves.
 *
 * Generated rather than hand-written because a hand-written index drifts the
 * moment a description changes, and a stale index misroutes silently — the one
 * failure mode a router cannot detect from the inside.
 *
 *   node .agents/scripts/build-catalog.mjs          # write
 *   node .agents/scripts/build-catalog.mjs --check  # fail if stale (for gates)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { parse as parseYaml } from "yaml";
import { listSkills } from "./skill-lint.mjs";

const ROOT = resolve(process.cwd());
const SKILLS = join(ROOT, ".agents/skills");
const OUT = join(SKILLS, "catalog.md");

const ORDER = { router: 0, knowledge: 1, task: 2, meta: 3 };
const HEADING = {
  router: "Router — the only entry point",
  knowledge: "Knowledge — load before acting",
  task: "Task — load with the work",
  meta: "Meta — the memory pipeline",
};

const rows = listSkills().map((name) => {
  const raw = readFileSync(join(SKILLS, name, "SKILL.md"), "utf8");
  const fm = parseYaml(/^---\n([\s\S]*?)\n---/.exec(raw)?.[1] ?? "") ?? {};
  return {
    name,
    description: String(fm.description ?? "").replace(/\s+/g, " ").trim(),
    type: fm.metadata?.type ?? "unknown",
    signal: fm.metadata?.verification_signal ?? "—",
  };
});

const lines = [
  "<!-- GENERATED by .agents/scripts/build-catalog.mjs — do not edit by hand. -->",
  "",
  "# Skill catalog",
  "",
  "Every task in this repository is dispatched through `project-router`. This index exists so the",
  "router can choose without reading each skill; the descriptions below are the only signal it has at",
  "selection time, which is why they name their triggers explicitly.",
  "",
  "Source of truth is `.agents/skills/`. `.claude/skills` is a symlink to it, so the same library is",
  "visible to any tool that reads either path.",
  "",
];

for (const type of Object.keys(ORDER)) {
  const group = rows.filter((r) => r.type === type);
  if (group.length === 0) continue;
  lines.push(`## ${HEADING[type] ?? type}`, "");
  for (const r of group) {
    lines.push(`### \`${r.name}\``, "", r.description, "");
    if (r.type !== "router") lines.push(`*Verified by:* \`${r.signal}\``, "");
  }
}

lines.push(
  "## How an update gets persisted",
  "",
  "A skill is edited only through the pipeline in `meta-skill-evolution`, and only when an objective",
  "signal external to the model agrees. The reason is that importance and truth are different things:",
  "a lean, well-scoped, correctly-cited rule can still be false, and once written it gets retrieved on",
  "similar tasks and followed. Defaulting to writing nothing is the safe failure.",
  "",
  "```",
  "importance → external signal → conflict check → eval gating → git commit",
  "```",
  "",
  "`node .agents/scripts/skill-verify.mjs <skill>` runs the gate and mints the token the write hook",
  "requires. `node .agents/scripts/skill-lint.mjs` checks form only.",
  "",
);

const content = lines.join("\n");

if (process.argv.includes("--check")) {
  const current = (() => {
    try {
      return readFileSync(OUT, "utf8");
    } catch {
      return "";
    }
  })();
  if (current !== content) {
    console.error("[build-catalog] catalog.md is stale — run `node .agents/scripts/build-catalog.mjs`");
    process.exit(1);
  }
  console.log("[build-catalog] catalog.md is current");
  process.exit(0);
}

writeFileSync(OUT, content, "utf8");
console.log(`[build-catalog] ${rows.length} skill(s) → .agents/skills/catalog.md`);
